### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by EntilZha** [scopely/asyncio-throttler#1]
Checking to see if this is unmaintained or its simply in a reasonably done state with nothing additional to do at the moment. Nice work!

**Comment by avram** [comment]
Scopely is using it on an internal project; can't say it's been terribly battle-tested (only a few months in production), but it is functionally complete.

**Comment by EntilZha** [comment]
Thanks for the quick reply. I found it through some googling to use for an asyncio compatible API access throttler for a side project and it seems perfect for the job.
